[package]
name = "orjson-test"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7", default-features = false, features = ["std", "serde"] }
itoa = { version = "1", default-features = false }
